[EPMEDU-1089] Create About page
interpmike/animeal_android pull request #115
Opened 2022-12-14 03:53 UTC by aklepets

[EPMEDU-1089] Create About page
Facebook and Instagram buttons open corresponding app if any. else open links in browser
Linkedin button opens browser. 
A web link leads to Linkedin for now. To be updated when the correct link is provided.

2022-12-14 17:35 UTC, Fileek commented on library/resources/src/main/res/drawable/icon_fb.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
We have `ic_facebook` already

2022-12-14 17:35 UTC, Fileek commented on library/resources/src/main/res/drawable/icon_inst.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Let's use the same format for all of our drawable names: `ic_instagram`

2022-12-14 17:35 UTC, Fileek commented on library/resources/src/main/res/drawable/icon_link.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
same as above

2022-12-14 17:35 UTC, Fileek commented on library/resources/src/main/res/drawable/icon_web.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
same as above

2022-12-14 17:35 UTC, Fileek commented on library/foundation/src/main/java/com/epmedu/animeal/foundation/button/AnimealSocialButton.kt
> +private fun FbAnimealSocialButtonPreview() {
Please put all previews together in one preview function and use column or row

2022-12-14 17:35 UTC, Fileek commented on feature/tabsflow/moreflow/about/build.gradle.kts
> +    implementation(libs.compose.material)
Sort by alphabetical order

2022-12-14 17:35 UTC, Fileek commented on feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/AboutScreenUI.kt
> +        modifier = modifier.fillMaxSize(),
Add `.statusBarsPadding()`

2022-12-14 17:35 UTC, Fileek commented on library/foundation/src/main/java/com/epmedu/animeal/foundation/button/AnimealSocialButton.kt
> +        modifier = modifier.size(62.dp),
Can you add gradient to match the design? It's similiar to `BottomAppBarFab`

2022-12-14 17:35 UTC, Fileek commented on feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/AboutScreenUI.kt
> +            text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, " +
There is `LoremIpsum` class for that :)

2022-12-14 17:35 UTC, Fileek commented on feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/AboutScreenUI.kt
> +            text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, " +
Same as above

2022-12-14 17:35 UTC, Fileek commented on feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/AboutScreenUI.kt
> +            modifier = Modifier.padding(start = 64.dp, end = 64.dp, top = 18.dp, bottom = 18.dp)
Can be replaced with `horizontal` and `vertical` arguments

2022-12-14 17:35 UTC, Fileek commented on feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/AboutScreenUI.kt
> +    Column(
Use `Scaffold` as a root with `topBar` so that inside it you can apply horizontal paddings on the whole column, not to each element

2022-12-14 17:35 UTC, Fileek commented on feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/AboutScreen.kt
> +        Intent(Intent.ACTION_VIEW, Uri.parse("https://www.facebook.com/animalprojectgeorgia/"))
Please extract all links to constants in `library/common/constants/Links`

2022-12-14 17:35 UTC, Fileek commented on feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/AboutScreen.kt
> +            try {
Don't repeat yourself. Extract the try-catch block to extension function `Context.startAppOrBrowser(
    appIntent: Intent,
    webIntent: Intent
)` in `library/extensions/Context`

2022-12-14 17:35 UTC, Fileek commented on feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/AboutScreen.kt
> +    val facebookWebIntent = remember {
What do you think about extracting all these intents to extension functions like `Context.openFacebook()`?

2022-12-14 20:38 UTC, Rogavactive approved these changes

2022-12-16 12:03 UTC, carlossantiagomenendez commented on feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/AboutScreenUI.kt
> +    onSocialWebClick: () -> Unit,
Hi! What do you think about only one listener that has an argument specifying the social media type? Something like: 
`OnSocialClick: (type: SocialMedia) -> Unit` and then having a sealed interface containing objects representing each social media. It's just a suggestion to reduce a little the function arguments.

2023-01-07 18:02 UTC, Fileek requested changes
Fix detekt please

2023-01-07 18:02 UTC, Fileek commented on feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/AboutScreenUI.kt
> +            .imePadding(),
Redundant padding

2023-01-07 18:02 UTC, Fileek commented on feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/AboutScreenUI.kt
> +            .imePadding(),
Content should be scrollable, check usecases in your ticket. 
But `Scaffold` does not support this, so you can replace it with `Column` and add `.verticalScroll(rememberScrollState())` to its modifier.

2023-01-07 18:02 UTC, Fileek commented on feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/AboutScreenUI.kt
> +                .statusBarsPadding()
Here the padding is not applied to topbar, please use it on the root element or topbar

2023-01-07 18:02 UTC, Fileek commented on feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/AboutScreenUI.kt
> +import androidx.compose.foundation.layout.*
Don't use wildcards

2023-01-07 18:02 UTC, Fileek commented on feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/AboutScreen.kt
> +import com.epmedu.animeal.extensions.*
Same

2023-01-07 18:02 UTC, Fileek commented on feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/AboutScreenUI.kt
> +    text2: String,
The text will be hardcoded in our resources (check jira ticket), there is no need to pass it

2023-01-07 18:02 UTC, Fileek commented on library/extensions/src/main/java/com/epmedu/animeal/extensions/Context.kt
> +import android.content.*
Same as above

2023-01-24 14:21 UTC, Fileek commented on feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/AboutScreenUI.kt
> +            SocialButtonsRow(
These two should be in the outer column

2023-01-24 14:21 UTC, Fileek commented on feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/AboutScreenUI.kt
> +            .padding(bottom = 32.dp, top = 8.dp)
Let's use vertical padding instead (32 dp with horizontal)

2023-01-24 15:04 UTC, Fileek approved these changes

2023-01-24 15:23 UTC, merged