[EPMEDU-797]: Auto-cancel feeding booking once the feeding timer expired
interpmike/animeal_android pull request #127
Opened 2023-02-07 16:22 UTC by Andrii-Chornyi

- Created dialog which appears on the timer expiration. The user is forcefully redirected to the Home screen from any other screen when the timer expires.
- Added Yellow coloring for reserved feeding points (partially covers EPMEDU-791) to demonstrate the change of state.

<details>
  <summary> Timer expires on home screen: </summary>

https://user-images.githubusercontent.com/112079677/217302200-41c7a16e-fb86-44b3-891a-7ea8d40109a4.mp4

</details>

<details>
  <summary> Timer expires on other screen: </summary>

https://user-images.githubusercontent.com/112079677/217302509-1c642452-ccf4-49fc-9871-48d24b0f9e04.mp4

</details>

2023-02-09 15:25 UTC, Fileek requested changes
Please refactor `onTimerExpire` lambda to using UI state + events approach

2023-02-09 15:25 UTC, Fileek commented on feature/home/src/main/java/com/epmedu/animeal/home/presentation/ui/map/RouteView.kt
> +            FeedingRouteState.TimerExpired -> {
You can connect these 2 blocks using `,`: `FeedingRouteState.Disabled, FeedingRouteState.TimerExpired -> ...`

2023-02-09 15:25 UTC, Fileek commented on feature/home/src/main/java/com/epmedu/animeal/home/presentation/ui/FeedingExpiredDialog.kt
> +    AlertDialog(
Can you move this dialog to `library` module, name it `AnimealAlertDialog` and rename current `AnimealAlertDialog` to `AnimealQuestionDialog`?

2023-02-09 15:25 UTC, Fileek commented on feature/home/src/main/java/com/epmedu/animeal/home/presentation/ui/FeedingExpiredDialog.kt
> +                onClick = { onConfirm() }
There is no need to create a lambda, just pass the callback: `onClick = onConfirm`

2023-02-14 22:30 UTC, Andrii-Chornyi commented
> Please refactor `onTimerExpire` lambda to using UI state + events approach

Moved all timer logic to tabs module

2023-02-14 22:34 UTC, Andrii-Chornyi commented on feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreenUI.kt
> -    scope.launch {
I'm uncertain that this condition was needed, as it completely blocks viewing bottom sheet during showing route to feeding points, according to my ticket to Figma designs accessing bottom sheet should be possible. Please, correct me if I'm wrong and it should remain

2023-02-20 23:02 UTC, Andrii-Chornyi commented on feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/feedingpoint/FeedingPointHandler.kt
> -    fun hideOtherFeedingPoints(feedingPoint: FeedingPointModel)
renamed this function as it got additional functionality of applying visual "reserved" look for feeding point

2023-02-21 14:46 UTC, Fileek reviewed
Please try to find a better solution to use a timer with flow

2023-02-21 14:46 UTC, Fileek commented on shared/feature/timer/src/main/java/com/epmedu/animeal/timer/data/repository/TimerRepository.kt
> +package com.epmedu.animeal.timer.data.repository
Please move the repository interface to the domain layer (create usecase package for usecases)

2023-02-24 20:01 UTC, Fileek approved these changes

2023-02-24 20:29 UTC, merged