EPMEDU-1576: Create UI for displaying attached photos
interpmike/animeal_android pull request #143
Opened 2023-03-07 16:11 UTC by n3gbx

- Implement Mark Feeding Done bottom sheet
- Display sheet when the feeding is active
- Scroll-left and Scroll-right actions for the list of taken photos
- "Finish" button is inactive until at least one photo hasn't been taken

https://user-images.githubusercontent.com/17089577/223480116-a6e800e2-d298-445b-b525-9445a0edb0ea.mp4

2023-03-07 17:06 UTC, Fileek requested changes
Please also do following things:
1. Fix expanded bottom sheet when feeding flow is disabled
2. Fix detekt
3. Rebase onto develop branch (we fixed lags)
4. Record demo again

2023-03-07 17:06 UTC, Fileek commented on feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreenUI.kt
> +                if (state.feedingRouteState is FeedingRouteState.Active) {
Please convert to when

2023-03-07 17:06 UTC, Fileek commented on feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/HomeState.kt
> +    val feedingPhotos: List<Uri> = listOf(),
Could be replaced with `emptyList()` function

2023-03-07 20:23 UTC, n3gbx commented on feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreenUI.kt
> +                if (state.feedingRouteState is FeedingRouteState.Active) {
Updated

2023-03-07 20:23 UTC, n3gbx commented on feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/HomeState.kt
> +    val feedingPhotos: List<Uri> = listOf(),
Updated

2023-03-07 20:54 UTC, n3gbx commented
> Please also do following things:
> 
> 1. Fix expanded bottom sheet when feeding flow is disabled
> 2. Fix detekt
> 3. Rebase onto develop branch (we fixed lags)
> 4. Record demo again

1,2,3 - done. 
4 - I can't record it again due to the absence of available feeding points. If you know how to reset their state please let me know

2023-03-08 10:02 UTC, Fileek requested changes
1. Bottom sheet is not showing after starting feeding flow and even after canceling.
2. To reset feeding point status, you need to wait 24 hours or do it manually in DynamoDB.

2023-03-08 13:43 UTC, Fileek approved these changes

2023-03-08 13:43 UTC, merged