[EPMEDU-1285]: Check if feeding is still in progress after app restart
interpmike/animeal_android pull request #150
Opened 2023-03-15 18:32 UTC by Fileek

2023-04-12 11:41 UTC, VEZE requested changes

2023-04-12 11:41 UTC, VEZE commented on shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/domain/repository/FeedingRepository.kt
> +    suspend fun getUserFeedings(): List<Feeding>?
can we remove/refactor nullability?

2023-04-12 16:14 UTC, Fileek commented on shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/domain/repository/FeedingRepository.kt
> +    suspend fun getUserFeedings(): List<Feeding>?
Done

2023-04-14 10:05 UTC, Andrii-Chornyi approved these changes

2023-04-14 10:10 UTC, merged