EPMEDU-731 - Updating requesting GPS permission and GPS location
interpmike/animeal_android pull request #164
Opened 2023-04-11 01:11 UTC by Andrii-Chornyi

Updating logic around accessing GPS permissions and enabling GPS locations.

2023-04-12 11:33 UTC, VEZE requested changes

2023-04-12 11:33 UTC, VEZE commented on library/extensions/src/main/java/com/epmedu/animeal/extensions/Context.kt
> +                    getActivity()!!,
remove !! expression

2023-04-12 11:33 UTC, VEZE commented on library/extensions/src/main/java/com/epmedu/animeal/extensions/Context.kt
> +        .addOnFailureListener(getActivity()!!) { resolvableException ->
remove !! expression

2023-04-12 11:33 UTC, VEZE commented on library/extensions/src/main/java/com/epmedu/animeal/extensions/Context.kt
> +        .addOnFailureListener(getActivity()!!) { resolvableException ->
addOnFailureListener can be used without getActivity()

2023-04-12 11:33 UTC, VEZE commented on library/extensions/src/main/java/com/epmedu/animeal/extensions/Context.kt
> +                val dummyRequestCode = 9999
move to const val, use appropriate name

2023-04-12 11:33 UTC, VEZE commented on library/extensions/src/main/java/com/epmedu/animeal/extensions/Context.kt
> +    val dummyInterval = 1000L
move to const val, use appropriate name

2023-04-12 11:33 UTC, VEZE commented on library/extensions/src/main/java/com/epmedu/animeal/extensions/Context.kt
> +        .addOnFailureListener(getActivity()!!) { resolvableException ->
naming -> resolvableException

2023-04-13 13:58 UTC, Fileek commented
It turned out that we have to implement auto-select of the closest feeding point. 
But let's do it after implementing taking and attaching photos.

2023-04-26 21:55 UTC, Fileek approved these changes

2023-04-26 21:56 UTC, merged