[EPMEDU-2511]: Disable phone number prefix selection for prod
interpmike/animeal_android pull request #248
Opened 2023-08-17 17:42 UTC by Fileek

- Added `isFlagClickable` to `ProfileState` and `EnterPhoneState`
  - Set `isFlagClickable` to `false` when flavor is prod

2023-08-17 18:50 UTC, ozkarram requested changes

2023-08-17 18:50 UTC, ozkarram commented on shared/feature/profile/src/main/java/com/epmedu/animeal/profile/presentation/ui/ProfileInputForm.kt
> +        isFlagClickable = isFlagClickable,
`isCountrySelectorClickable`?

2023-08-17 18:50 UTC, ozkarram commented on app/src/main/java/com/epmedu/animeal/component/BuildConfigProviderImpl.kt
> +    override val isProd: Boolean = BuildConfig.FLAVOR == PROD_FLAVOR
isProdFlavor?

2023-08-17 18:54 UTC, Fileek commented on shared/feature/profile/src/main/java/com/epmedu/animeal/profile/presentation/ui/ProfileInputForm.kt
> +        isFlagClickable = isFlagClickable,
Renamed

2023-08-17 18:54 UTC, Fileek commented on app/src/main/java/com/epmedu/animeal/component/BuildConfigProviderImpl.kt
> +    override val isProd: Boolean = BuildConfig.FLAVOR == PROD_FLAVOR
Renamed

2023-08-18 15:36 UTC, ozkarram approved these changes

2023-08-18 15:42 UTC, merged