Remove base module
interpmike/animeal_android pull request #26
Opened 2022-07-06 11:51 UTC by egorikftp

2022-07-06 12:17 UTC, Fileek requested changes
Please move fonts and strings to resources module

2022-07-07 08:29 UTC, Fileek approved these changes

2022-07-07 08:42 UTC, Fileek requested changes
Please fix imports for TextInputField in input package of foundation module

2022-07-07 09:01 UTC, Fileek approved these changes

2022-07-07 09:08 UTC, DoTheMonkeyBusiness approved these changes

2022-07-12 13:20 UTC, merged