[EPMEDU-1998]: Reduce size of downloaded images
interpmike/animeal_android pull request #266
Opened 2024-01-15 12:02 UTC by Fileek

- Prevented image duplication in cache by using disk cache keys
  - Moved `StorageApi` to a separate module networkstorage
  - Created `NetworkFile` wrapper

2024-01-18 16:55 UTC, ozkarram requested changes
Just some naming changes

2024-01-18 16:55 UTC, ozkarram commented on shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/mapper/DataToDomainFeedingPointMapper.kt
> +    getImageFromName: suspend (String) -> NetworkFile?,
rename to `getImageFrom`

2024-01-18 16:55 UTC, ozkarram commented on shared/feature/networkstorage/src/main/java/com/epmedu/animeal/networkstorage/data/api/StorageApi.kt
> +    suspend fun getUrlFromFileName(fileName: String): String
`getUrlFrom`

2024-01-18 18:55 UTC, Fileek commented on shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/mapper/DataToDomainFeedingPointMapper.kt
> +    getImageFromName: suspend (String) -> NetworkFile?,
Done

2024-01-18 18:55 UTC, Fileek commented on shared/feature/networkstorage/src/main/java/com/epmedu/animeal/networkstorage/data/api/StorageApi.kt
> +    suspend fun getUrlFromFileName(fileName: String): String
Done

2024-01-19 16:05 UTC, ozkarram approved these changes

2024-01-19 16:06 UTC, merged