[EPMEDU-3288]: Back navigation to Sign up is not restricted
interpmike/animeal_android pull request #269
Opened 2024-01-24 15:15 UTC by Fileek

- Prevented double navigation on logout which caused keeping Onboarding screen in the backstack

2024-01-24 20:29 UTC, ozkarram requested changes

2024-01-24 20:29 UTC, ozkarram commented on feature/tabsflow/moreflow/account/src/main/java/com/epmedu/animeal/tabs/more/account/AccountScreenEvent.kt
> +    Logout, Delete, ToastShown, NavigatedToOnboarding
`GoToOnboarding`

2024-01-24 20:51 UTC, Fileek commented on feature/tabsflow/moreflow/account/src/main/java/com/epmedu/animeal/tabs/more/account/AccountScreenEvent.kt
> +    Logout, Delete, ToastShown, NavigatedToOnboarding
Done

2024-01-25 16:54 UTC, ozkarram approved these changes

2024-01-25 16:54 UTC, merged